baseURL = "http://fannyjourdan.github.io/"
languageCode = "en-us"
title = "Fanny Jourdan"
theme = "PaperMod"

# [params.profileMode]
# enabled = true
# title = "About me" # optional default will be site title
# subtitle = "This is subtitle"
# imageUrl = "<image link>" # optional
# imageTitle = "<title of image as alt>" # optional
# imageWidth = 120 # custom size
# imageHeight = 120 # custom size

[params.homeInfoParams]
Title = "Hi! My name is Fanny Jourdan."
Content ='''
I am PhD <br /> Student in mathematics and computer science at Institut
de Recherche en Informatique de Toulouse and Artificial and
Natural Intelligence Toulouse Institut.
I'm also a member of the brilliant DEEL team ðŸ¤©.
My two amazing supervisors are Nicholas Asher and Laurent Risser.
My interest topics are Fairness, Explainability and Robustness of 
Natural Language Processing algorithms.
Previously I did a masterâ€™s in mathematics and data sciences 
at Ecole Polytechnique, where I co-founded the Artificial 
Intelligence Alumni Association (AlumnIA).
Then I did another masterâ€™s in digital economics and innovation
at Paris-Dauphine University.I'm committed to the fight against
gender inequality in STEM ðŸ¤– (see: ANITI's gender equality commission and women and mathematics association). In my spare time,
I practice crossfit and weightlifting.
I also danced ballet for over 17 years before that."
'''


[[params.socialIcons]]
name = "cv"
url = "<link2>"

[[params.socialIcons]]
name = "email"
url = "<mailto:fanny.jourdan@irit.fr>"

[[params.socialIcons]]
name = "googlescholar"
url = "<https://scholar.google.com/citations?user=ntU8A30AAAAJ&hl=fr>"

[[params.socialIcons]]
name = "github"
url = "<https://github.com/fanny-jourdan>"

[[params.socialIcons]]
name = "twitter"
url = "<https://twitter.com/Fannyjrd_>"

[[params.socialIcons]]
name = "linkedin"
url = "<https://www.linkedin.com/in/fanny-jourdan/>"

	
